### ISSUE TITLE
Githubからのセキュリティ警告の対処

### ISSUE THREAD

**Issue by puremoru** [puremoru/PickBook#22]
## 概要
Githubからの以下の警告が出た。
![image](https://user-images.githubusercontent.com/22650969/42197128-5220898e-7ebc-11e8-83da-252fc67e6f63.png)

おそらくgemのバージョンに関連するもの。`bundle update`すれば直りそう🤔
## 目的
セキュリティ向上
## 提案内容
$ bundle update

**Comment by puremoru** [comment]
## 参考リンク
https://qiita.com/taktakfu/items/471333d3dd2c9e935949

**Comment by isoflabon** [comment]
自分のでは出てないから確認できてないけど
`$ bundle update` をする前にどのgemが原因なのか確認したい。

**Comment by puremoru** [comment]
@isoflabon 
![image](https://user-images.githubusercontent.com/22650969/43304591-b5245eec-91af-11e8-86b2-16b6a62b11b6.png)

これが原因っぽい
